config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  # Force the edit, update, show and delete actions to run the method 
  # set_article before they execute anything else.
  # The method will retun @article.find(params[:id]) line of code, which will 
  # grab the article regarding to the id that is being passed through the URL(Route)
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  # The require_user was created on application controller, so is accessible from any other 
  # controller. It returns the user object that is logged in (from session). It 
  # It gets the user before execute the crud actions, to make sure the user can only 
  # manage their own articles
  before_action :require_user, except: [:index, :show]
  # It prevents the users to access other user's articles through the url, and delete or edit it.
  # This reuqire_same_user was create down below that controller/class.
  before_action :require_same_user, only: [:edit, :destroy, :update]
  
  def index
    # @articles new instance variable is going to have all articles from the databse
    # The paginate method is used to insert pagination on the template
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  
  def new 
    @article = Article.new
  end
  
  def edit
    # @article = Article.find(params[:id])
  end
  
  def update
    # @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def create 
    #debugger
    # Works like a console.log, to print the content from the form
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      # Display a message to the user if the message was created.
      flash[:success] = "Article was successfully created!"
      redirect_to article_path(@article)  
    else
      render 'new'
    end
  end
  
  def show 
    # @article = Article.find(params[:id])
  end
  
  def destroy
    # @article = Article.find(params[:id]) 
    @article.destroy
    flash[:danger] = "Article was successfully deleted."
    redirect_to articles_path
  end
  
    private def article_params
    params.require(:article).permit(:title, :description, category_ids: []) 
  end
  
  private def set_article
    @article = Article.find(params[:id])
  end
  
  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own articles."
      redirect_to root_path
    end
  end
  
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well weel-lg">
        
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        
        <div class="article-body">
          <%= truncate(article.description, length:100) %>
          <div class="article-meta-details">
            <small>
              Created by: <%= article.user.username if article.user %>
              <%= time_ago_in_words(article.created_at) %> ago, 
              Last Updated: <%= time_ago_in_words(article.updated_at) %> ago.
            </small>
          </div>
        </div>
        
        <% if article.categories.any? %>
          <p>Categories: <%= render article.categories %></p>
        <% end %>
        
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="article-actions">
            <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete Article", article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
        
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<!-- As this is a module help form, it fills the data regarding to the article id got from the route(URL) -->
<!-- The variable instance @articles eas created on articles_controller "new" method -->
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of Article", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of the Article" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg" %> <!-- It submits to the create method on articles_controller -->
        </div>
      </div>
      
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel Request and return to Articles Listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Articles List</h1>

<div align="center">
  <%= will_paginate %>
</div>

<%= render 'article', obj: @articles %>

<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"> Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  
  <% if @article.user %>
    <ul class="listing">
      <div class="row center">
        <div class="col-md-4 col-md-offset-4">
          <li>Created by: </li>
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <li class="article-title">
            <%= link_to @article.user.username, user_path(@article.user) %>
          </li>
          <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  
  
  
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
  
  <%= simple_format(@article.description) %>
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>
  <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete Article", article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %>
    <% end %>  
      <%= link_to "View all Articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
  
</div>