config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  resources :categories, except: [:destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :required_admin, except: [:index, :show]
  
  def index
    # Adding pagination to the categories page
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category Created Successfully"
      redirect_to categories_path
    else
      render 'new'  
    end
  end
  
  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end
  
  def edit 
    @category = Category.find(params[:id])  
  end
  
  def update
  @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated."
      redirect_to categories_path(@category)
    else
      render 'edit'
    end
  end
  
  # Grab the data from the form, where a new category is inserted.
  private 
  def category_params
    params.require(:category).permit(:name)
  end
  
  def required_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp; <span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<!-- As this is a module help form, it fills the data regarding to the article id got from the route(URL) -->
<!-- The variable instance @category eas created on articles_controller "new" method -->
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :name %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Category title", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg" %> <!-- It submits to the create method on articles_controller -->
        </div>
      </div>
      
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel Request and return to Articles Listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit existing Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Listing All Categories</h1>

<div align="center">
  <%= will_paginate %>
    <% @categories.each do |category| %>
      <ul class="listing">
        <div class="row">
          <div class = "well col-md-4 col-md-offset-4">
            <li class = "article-title">
              <%= link_to "#{category.name}", category_path(category) %>
            </li>
            <li><small><%= pluralize(category.articles.count, "article") if category.articles %></small></li>
          </div>
        </div>
      </ul>
    <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align=center>Create new Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>

<div align="center">
  <% if logged_in? and current_user.admin? %>
    <div class="row">
      <span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
      <%= will_paginate @category_articles %>
    </div>
  <% end %>
</div>

<%= render 'articles/article', obj: @category_articles %>

<div align="center">
  <%= will_paginate @category_articles %>
</div>